// Code generated by gotemplate. DO NOT EDIT.

package main

import "errors"

// template type Stack(A)

type StudentStack struct {
	data []*Student
}

func (s *StudentStack) Push(value *Student) {
	s.data = append(s.data, value)
}

func (s *StudentStack) Pop() (*Student, error) {
	length := len(s.data)
	if length == 0 {
		return nil, errors.New("Stack is empty")
	}
	value := s.data[length-1]
	s.data = s.data[:length-1]
	return value, nil
}

func NewStudentStack() *StudentStack {
	return &StudentStack{
		data: []*Student{},
	}
}
