// Code generated by protoc-gen-go. DO NOT EDIT.
// source: additional/protogen/pkga/a.proto

package pkga // import "kuitest/additional/protogen/pkga"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type HelloRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a_c925c9abb7825f2d, []int{0}
}
func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest.Unmarshal(m, b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
}
func (dst *HelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest.Merge(dst, src)
}
func (m *HelloRequest) XXX_Size() int {
	return xxx_messageInfo_HelloRequest.Size(m)
}
func (m *HelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type HelloResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloResponse) Reset()         { *m = HelloResponse{} }
func (m *HelloResponse) String() string { return proto.CompactTextString(m) }
func (*HelloResponse) ProtoMessage()    {}
func (*HelloResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a_c925c9abb7825f2d, []int{1}
}
func (m *HelloResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloResponse.Unmarshal(m, b)
}
func (m *HelloResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloResponse.Marshal(b, m, deterministic)
}
func (dst *HelloResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloResponse.Merge(dst, src)
}
func (m *HelloResponse) XXX_Size() int {
	return xxx_messageInfo_HelloResponse.Size(m)
}
func (m *HelloResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HelloResponse proto.InternalMessageInfo

func (m *HelloResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Coordinates struct {
	Latitude             float64  `protobuf:"fixed64,1,opt,name=Latitude,proto3" json:"Latitude,omitempty"`
	Longitude            float64  `protobuf:"fixed64,2,opt,name=Longitude,proto3" json:"Longitude,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Coordinates) Reset()         { *m = Coordinates{} }
func (m *Coordinates) String() string { return proto.CompactTextString(m) }
func (*Coordinates) ProtoMessage()    {}
func (*Coordinates) Descriptor() ([]byte, []int) {
	return fileDescriptor_a_c925c9abb7825f2d, []int{2}
}
func (m *Coordinates) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Coordinates.Unmarshal(m, b)
}
func (m *Coordinates) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Coordinates.Marshal(b, m, deterministic)
}
func (dst *Coordinates) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Coordinates.Merge(dst, src)
}
func (m *Coordinates) XXX_Size() int {
	return xxx_messageInfo_Coordinates.Size(m)
}
func (m *Coordinates) XXX_DiscardUnknown() {
	xxx_messageInfo_Coordinates.DiscardUnknown(m)
}

var xxx_messageInfo_Coordinates proto.InternalMessageInfo

func (m *Coordinates) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *Coordinates) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func init() {
	proto.RegisterType((*HelloRequest)(nil), "pkgapb.HelloRequest")
	proto.RegisterType((*HelloResponse)(nil), "pkgapb.HelloResponse")
	proto.RegisterType((*Coordinates)(nil), "pkgapb.Coordinates")
}

func init() { proto.RegisterFile("additional/protogen/pkga/a.proto", fileDescriptor_a_c925c9abb7825f2d) }

var fileDescriptor_a_c925c9abb7825f2d = []byte{
	// 219 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0x31, 0x4b, 0x03, 0x41,
	0x10, 0x85, 0xb9, 0x18, 0x4e, 0x33, 0x6a, 0x33, 0x28, 0x84, 0x60, 0x71, 0x6c, 0xa5, 0xcd, 0x1d,
	0xc4, 0xce, 0x32, 0x16, 0x5a, 0x44, 0x91, 0x2b, 0xed, 0x26, 0xdc, 0xb0, 0x2c, 0x77, 0xee, 0xac,
	0xd9, 0xb9, 0xff, 0xe1, 0x4f, 0x16, 0x77, 0x3d, 0x15, 0x21, 0xdd, 0x7e, 0xef, 0x3d, 0xd8, 0x8f,
	0x81, 0x8a, 0xba, 0xce, 0xa9, 0x13, 0x4f, 0x43, 0x13, 0xf6, 0xa2, 0x62, 0xd9, 0x37, 0xa1, 0xb7,
	0xd4, 0x50, 0x9d, 0x18, 0xcb, 0x2f, 0x0a, 0x3b, 0x63, 0xe0, 0xec, 0x91, 0x87, 0x41, 0x5a, 0x7e,
	0x1f, 0x39, 0x2a, 0x22, 0xcc, 0x9f, 0xe9, 0x8d, 0x97, 0x45, 0x55, 0x5c, 0x2f, 0xda, 0xf4, 0x36,
	0x37, 0x70, 0xfe, 0xbd, 0x89, 0x41, 0x7c, 0x64, 0x5c, 0xc2, 0xf1, 0x13, 0xc7, 0x48, 0x76, 0xda,
	0x4d, 0x68, 0x1e, 0xe0, 0xf4, 0x5e, 0x64, 0xdf, 0x39, 0x4f, 0xca, 0x11, 0x57, 0x70, 0xb2, 0x25,
	0x75, 0x3a, 0x76, 0x79, 0x59, 0xb4, 0x3f, 0x8c, 0x57, 0xb0, 0xd8, 0x8a, 0xb7, 0xb9, 0x9c, 0xa5,
	0xf2, 0x37, 0x58, 0x6f, 0x60, 0xfe, 0xd2, 0x5b, 0xc2, 0x3b, 0x28, 0xd3, 0xdf, 0x6b, 0xbc, 0xa8,
	0xb3, 0x72, 0xfd, 0xd7, 0x77, 0x75, 0xf9, 0x2f, 0xcd, 0x86, 0xe6, 0xe8, 0x63, 0x56, 0x6c, 0xcc,
	0x6b, 0xd5, 0x8f, 0x4e, 0x39, 0x6a, 0x73, 0xe8, 0x1e, 0xbb, 0x32, 0xe1, 0xed, 0x67, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x95, 0xa2, 0xdd, 0x27, 0x32, 0x01, 0x00, 0x00,
}
