// Code generated by protoc-gen-go. DO NOT EDIT.
// source: test.proto

package main

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
import any "github.com/golang/protobuf/ptypes/any"
import _ "github.com/golang/protobuf/ptypes/empty"
import _ "github.com/golang/protobuf/ptypes/timestamp"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type HelloRequest struct {
	I32                  int32          `protobuf:"varint,1,opt,name=i32,proto3" json:"i32,omitempty"`
	I64                  int64          `protobuf:"varint,2,opt,name=i64,proto3" json:"i64,omitempty"`
	B                    bool           `protobuf:"varint,3,opt,name=b,proto3" json:"b,omitempty"`
	F                    float32        `protobuf:"fixed32,4,opt,name=f,proto3" json:"f,omitempty"`
	D                    float64        `protobuf:"fixed64,5,opt,name=d,proto3" json:"d,omitempty"`
	Name                 string         `protobuf:"bytes,10,opt,name=Name,proto3" json:"Name,omitempty"`
	Hr                   *HelloResponse `protobuf:"bytes,15,opt,name=hr,proto3" json:"hr,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_test_a9880e389eaa9a0d, []int{0}
}
func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest.Unmarshal(m, b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
}
func (dst *HelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest.Merge(dst, src)
}
func (m *HelloRequest) XXX_Size() int {
	return xxx_messageInfo_HelloRequest.Size(m)
}
func (m *HelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

func (m *HelloRequest) GetI32() int32 {
	if m != nil {
		return m.I32
	}
	return 0
}

func (m *HelloRequest) GetI64() int64 {
	if m != nil {
		return m.I64
	}
	return 0
}

func (m *HelloRequest) GetB() bool {
	if m != nil {
		return m.B
	}
	return false
}

func (m *HelloRequest) GetF() float32 {
	if m != nil {
		return m.F
	}
	return 0
}

func (m *HelloRequest) GetD() float64 {
	if m != nil {
		return m.D
	}
	return 0
}

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *HelloRequest) GetHr() *HelloResponse {
	if m != nil {
		return m.Hr
	}
	return nil
}

type HelloResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloResponse) Reset()         { *m = HelloResponse{} }
func (m *HelloResponse) String() string { return proto.CompactTextString(m) }
func (*HelloResponse) ProtoMessage()    {}
func (*HelloResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_test_a9880e389eaa9a0d, []int{1}
}
func (m *HelloResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloResponse.Unmarshal(m, b)
}
func (m *HelloResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloResponse.Marshal(b, m, deterministic)
}
func (dst *HelloResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloResponse.Merge(dst, src)
}
func (m *HelloResponse) XXX_Size() int {
	return xxx_messageInfo_HelloResponse.Size(m)
}
func (m *HelloResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HelloResponse proto.InternalMessageInfo

func (m *HelloResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type SelfDescribingMessage struct {
	// Set of FileDescriptorProtos which describe the type and its dependencies.
	DescriptorSet *descriptor.FileDescriptorSet `protobuf:"bytes,1,opt,name=descriptor_set,json=descriptorSet,proto3" json:"descriptor_set,omitempty"`
	// The message and its type, encoded as an Any message.
	Message              *any.Any `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SelfDescribingMessage) Reset()         { *m = SelfDescribingMessage{} }
func (m *SelfDescribingMessage) String() string { return proto.CompactTextString(m) }
func (*SelfDescribingMessage) ProtoMessage()    {}
func (*SelfDescribingMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_test_a9880e389eaa9a0d, []int{2}
}
func (m *SelfDescribingMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SelfDescribingMessage.Unmarshal(m, b)
}
func (m *SelfDescribingMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SelfDescribingMessage.Marshal(b, m, deterministic)
}
func (dst *SelfDescribingMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SelfDescribingMessage.Merge(dst, src)
}
func (m *SelfDescribingMessage) XXX_Size() int {
	return xxx_messageInfo_SelfDescribingMessage.Size(m)
}
func (m *SelfDescribingMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_SelfDescribingMessage.DiscardUnknown(m)
}

var xxx_messageInfo_SelfDescribingMessage proto.InternalMessageInfo

func (m *SelfDescribingMessage) GetDescriptorSet() *descriptor.FileDescriptorSet {
	if m != nil {
		return m.DescriptorSet
	}
	return nil
}

func (m *SelfDescribingMessage) GetMessage() *any.Any {
	if m != nil {
		return m.Message
	}
	return nil
}

func init() {
	proto.RegisterType((*HelloRequest)(nil), "main.HelloRequest")
	proto.RegisterType((*HelloResponse)(nil), "main.HelloResponse")
	proto.RegisterType((*SelfDescribingMessage)(nil), "main.SelfDescribingMessage")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// HelloServiceClient is the client API for HelloService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HelloServiceClient interface {
	Hello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error)
}

type helloServiceClient struct {
	cc *grpc.ClientConn
}

func NewHelloServiceClient(cc *grpc.ClientConn) HelloServiceClient {
	return &helloServiceClient{cc}
}

func (c *helloServiceClient) Hello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error) {
	out := new(HelloResponse)
	err := c.cc.Invoke(ctx, "/main.HelloService/Hello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HelloServiceServer is the server API for HelloService service.
type HelloServiceServer interface {
	Hello(context.Context, *HelloRequest) (*HelloResponse, error)
}

func RegisterHelloServiceServer(s *grpc.Server, srv HelloServiceServer) {
	s.RegisterService(&_HelloService_serviceDesc, srv)
}

func _HelloService_Hello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloServiceServer).Hello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.HelloService/Hello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloServiceServer).Hello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _HelloService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "main.HelloService",
	HandlerType: (*HelloServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Hello",
			Handler:    _HelloService_Hello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "test.proto",
}

func init() { proto.RegisterFile("test.proto", fileDescriptor_test_a9880e389eaa9a0d) }

var fileDescriptor_test_a9880e389eaa9a0d = []byte{
	// 381 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x50, 0xbd, 0xce, 0xd3, 0x30,
	0x14, 0xd5, 0x4d, 0x5b, 0x3e, 0xea, 0xef, 0x6b, 0x41, 0x06, 0x84, 0x29, 0x48, 0x58, 0x61, 0x09,
	0x0c, 0x89, 0x48, 0x11, 0x03, 0x1b, 0x52, 0x85, 0x60, 0x80, 0xc1, 0x9d, 0x98, 0x90, 0xd3, 0xdc,
	0xa4, 0x96, 0x12, 0x3b, 0xc4, 0x6e, 0xa5, 0xae, 0x3c, 0x01, 0x02, 0xf1, 0x64, 0xbc, 0x02, 0x0f,
	0x82, 0xe2, 0x26, 0x40, 0xcb, 0xb7, 0xdd, 0x73, 0xcf, 0xb9, 0x3f, 0xe7, 0x10, 0xe2, 0xd0, 0xba,
	0xb8, 0x69, 0x8d, 0x33, 0x74, 0x5c, 0x4b, 0xa5, 0x17, 0x0f, 0x4b, 0x63, 0xca, 0x0a, 0x13, 0xdf,
	0xcb, 0x76, 0x45, 0x82, 0x75, 0xe3, 0x0e, 0x47, 0xc9, 0xe2, 0xf1, 0x39, 0xe9, 0x54, 0x8d, 0xd6,
	0xc9, 0xba, 0xe9, 0x05, 0x8f, 0x7a, 0x81, 0x6c, 0x54, 0x22, 0xb5, 0x36, 0x4e, 0x3a, 0x65, 0xb4,
	0xed, 0xd9, 0x07, 0xe7, 0xe3, 0x52, 0x0f, 0x9b, 0xf9, 0x39, 0x95, 0xa3, 0xdd, 0xb4, 0xaa, 0x71,
	0xa6, 0x3d, 0x2a, 0xc2, 0x1f, 0x40, 0xae, 0xde, 0x62, 0x55, 0x19, 0x81, 0x9f, 0x77, 0x68, 0x1d,
	0xbd, 0x4d, 0x46, 0x6a, 0x99, 0x32, 0xe0, 0x10, 0x4d, 0x44, 0x57, 0xfa, 0xce, 0xcb, 0x17, 0x2c,
	0xe0, 0x10, 0x8d, 0x44, 0x57, 0xd2, 0x2b, 0x02, 0x19, 0x1b, 0x71, 0x88, 0x6e, 0x0a, 0xc8, 0x3a,
	0x54, 0xb0, 0x31, 0x87, 0x28, 0x10, 0x50, 0x74, 0x28, 0x67, 0x13, 0x0e, 0x11, 0x08, 0xc8, 0x29,
	0x25, 0xe3, 0x0f, 0xb2, 0x46, 0x46, 0x38, 0x44, 0x53, 0xe1, 0x6b, 0xfa, 0x84, 0x04, 0xdb, 0x96,
	0xdd, 0xe2, 0x10, 0x5d, 0xa6, 0x77, 0xe2, 0x2e, 0x9e, 0xb8, 0xff, 0xc0, 0x36, 0x46, 0x5b, 0x14,
	0xc1, 0xb6, 0x0d, 0x9f, 0x92, 0xd9, 0x49, 0x93, 0x32, 0x72, 0xf1, 0x1e, 0xad, 0x95, 0x25, 0xfa,
	0xdf, 0xa6, 0x62, 0x80, 0xe1, 0x37, 0x20, 0xf7, 0xd6, 0x58, 0x15, 0x2b, 0xef, 0x2d, 0x53, 0xba,
	0xec, 0x19, 0xfa, 0x8e, 0xcc, 0xff, 0x1a, 0xfe, 0x64, 0xd1, 0xf9, 0xd1, 0xcb, 0x34, 0x8c, 0x8f,
	0xb9, 0xc4, 0x43, 0x2e, 0xf1, 0x1b, 0x55, 0xe1, 0xea, 0x8f, 0x74, 0x8d, 0x4e, 0xcc, 0xf2, 0x7f,
	0x21, 0x8d, 0xc9, 0x45, 0xdd, 0x9f, 0x0f, 0xfc, 0x8e, 0xbb, 0xff, 0xed, 0x78, 0xad, 0x0f, 0x62,
	0x10, 0xa5, 0x1f, 0xfb, 0x58, 0xd7, 0xd8, 0xee, 0xd5, 0xa6, 0x7b, 0x65, 0xe2, 0x31, 0xa5, 0x27,
	0x8e, 0x7d, 0xe6, 0x8b, 0xeb, 0x52, 0x08, 0xef, 0x7f, 0xf9, 0xf9, 0xeb, 0x7b, 0x30, 0x0f, 0xa7,
	0xc9, 0xfe, 0x79, 0xb2, 0xed, 0xa8, 0x57, 0xf0, 0xec, 0x6b, 0x00, 0xd9, 0x0d, 0x7f, 0x71, 0xf9,
	0x3b, 0x00, 0x00, 0xff, 0xff, 0x46, 0x81, 0x51, 0xb6, 0x66, 0x02, 0x00, 0x00,
}
