// Code generated by protoc-gen-go. DO NOT EDIT.
// source: additional/protogen/pkgb/b.proto

package pkgb // import "kuitest/additional/protogen/pkgb"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import pkga "kuitest/additional/protogen/pkga"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// HelloRequest from public import a.proto
type HelloRequest = pkga.HelloRequest

// HelloResponse from public import a.proto
type HelloResponse = pkga.HelloResponse

// Coordinates from public import a.proto
type Coordinates = pkga.Coordinates

type Coordinates struct {
	Latitude             float64            `protobuf:"fixed64,1,opt,name=Latitude,proto3" json:"Latitude,omitempty"`
	Longitude            float64            `protobuf:"fixed64,2,opt,name=Longitude,proto3" json:"Longitude,omitempty"`
	HelloRequest         *pkga.HelloRequest `protobuf:"bytes,3,opt,name=HelloRequest,proto3" json:"HelloRequest,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Coordinates) Reset()         { *m = Coordinates{} }
func (m *Coordinates) String() string { return proto.CompactTextString(m) }
func (*Coordinates) ProtoMessage()    {}
func (*Coordinates) Descriptor() ([]byte, []int) {
	return fileDescriptor_b_6b89da4587d91b74, []int{0}
}
func (m *Coordinates) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Coordinates.Unmarshal(m, b)
}
func (m *Coordinates) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Coordinates.Marshal(b, m, deterministic)
}
func (dst *Coordinates) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Coordinates.Merge(dst, src)
}
func (m *Coordinates) XXX_Size() int {
	return xxx_messageInfo_Coordinates.Size(m)
}
func (m *Coordinates) XXX_DiscardUnknown() {
	xxx_messageInfo_Coordinates.DiscardUnknown(m)
}

var xxx_messageInfo_Coordinates proto.InternalMessageInfo

func (m *Coordinates) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *Coordinates) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func (m *Coordinates) GetHelloRequest() *pkga.HelloRequest {
	if m != nil {
		return m.HelloRequest
	}
	return nil
}

func init() {
	proto.RegisterType((*Coordinates)(nil), "pkgbpb.Coordinates")
}

func init() { proto.RegisterFile("additional/protogen/pkgb/b.proto", fileDescriptor_b_6b89da4587d91b74) }

var fileDescriptor_b_6b89da4587d91b74 = []byte{
	// 209 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x48, 0x4c, 0x49, 0xc9,
	0x2c, 0xc9, 0xcc, 0xcf, 0x4b, 0xcc, 0xd1, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0x4f, 0x4f, 0xcd, 0xd3,
	0x2f, 0xc8, 0x4e, 0x4f, 0xd2, 0x4f, 0xd2, 0x03, 0xf3, 0x85, 0xd8, 0x40, 0xbc, 0x82, 0x24, 0x29,
	0xf6, 0x44, 0x88, 0x80, 0x52, 0x23, 0x23, 0x17, 0xb7, 0x73, 0x7e, 0x7e, 0x51, 0x4a, 0x66, 0x5e,
	0x62, 0x49, 0x6a, 0xb1, 0x90, 0x14, 0x17, 0x87, 0x4f, 0x62, 0x49, 0x66, 0x49, 0x69, 0x4a, 0xaa,
	0x04, 0xa3, 0x02, 0xa3, 0x06, 0x63, 0x10, 0x9c, 0x2f, 0x24, 0xc3, 0xc5, 0xe9, 0x93, 0x9f, 0x97,
	0x0e, 0x91, 0x64, 0x02, 0x4b, 0x22, 0x04, 0x84, 0x2c, 0xb8, 0x78, 0x3c, 0x52, 0x73, 0x72, 0xf2,
	0x83, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x24, 0x98, 0x15, 0x18, 0x35, 0xb8, 0x8d, 0x44, 0xf4,
	0x0a, 0xb2, 0xd3, 0x13, 0x0b, 0x92, 0xf4, 0x90, 0xe5, 0x82, 0x50, 0x54, 0x1a, 0x39, 0x71, 0xb1,
	0x04, 0x64, 0xa7, 0x27, 0x09, 0x59, 0x71, 0xb1, 0x81, 0xc5, 0x8d, 0x84, 0xb0, 0xea, 0x92, 0x12,
	0x45, 0x13, 0x2d, 0x2e, 0xc8, 0xcf, 0x2b, 0x4e, 0x55, 0x62, 0x9e, 0xc0, 0xc4, 0xe8, 0xa4, 0x14,
	0xa5, 0x90, 0x5d, 0x9a, 0x59, 0x92, 0x5a, 0x5c, 0xa2, 0x8f, 0x2b, 0x10, 0x02, 0x18, 0x92, 0xd8,
	0xc0, 0x02, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x60, 0xb5, 0x46, 0x1e, 0x29, 0x01, 0x00,
	0x00,
}
